### ISSUE TITLE
dynamic-shape gather leads to illegal mhlo error, but is it actually illegal?

### ISSUE THREAD

**Issue by mattjj** [openxla/iree#10334]
### What happened?

I'm working with targeting MHLO & IREE dynamic shapes from JAX, and in particular currently working on generating gather operations involving dynamic shapes, compiling those programs with IREE, and executing them with the prototype JAX+IREE backend.

In the course of that work I generated this MHLO program, on which the IREE stack errors. But I'm not sure if this MHLO program is actually invalid, or if it's an IREE bug.

I pasted the IREE-generated reproducer files below. While it's not strictly needed to address the question, FYI the JAX program I used to generate this MHLO program (which only works on a branch) looks like this:

```python
from functools import partial
import jax
import jax.numpy as jnp
jax.config.update('jax_dynamic_shapes', True)
jax.config.update('jax_platforms', 'iree')

x = jnp.arange(3.)
idxs = jnp.arange(3)

def f(i):
  return x[i]

@partial(jax.jit, abstracted_axes=('n',))
def g(idxs):
  return jax.vmap(f)(idxs)

g(idxs)
```

The MHLO program generated is

```
module @jit_g.2 {
  func.func public @main(%arg0: tensor<i32>, %arg1: tensor<?xi32>) -> tensor<?xf32> {
    %0 = mhlo.constant dense<[0.000000e+00, 1.000000e+00, 2.000000e+00]> : tensor<3xf32>
    %1 = mhlo.constant dense<0> : tensor<i32>
    %2 = mhlo.convert %arg0 : tensor<i32>
    %3 = "mhlo.reshape"(%2) : (tensor<i32>) -> tensor<1xi32>
    %4 = "mhlo.dynamic_broadcast_in_dim"(%arg1, %3) {broadcast_dimensions = dense<0> : tensor<1xi64>} : (tensor<?xi32>, tensor<1xi32>) -> tensor<?xi32>
    %5 = mhlo.convert %arg0 : tensor<i32>
    %6 = "mhlo.reshape"(%5) : (tensor<i32>) -> tensor<1xi32>
    %7 = "mhlo.dynamic_broadcast_in_dim"(%1, %6) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>, tensor<1xi32>) -> tensor<?xi32>
    %8 = "mhlo.compare"(%4, %7) {compare_type = #mhlo<comparison_type SIGNED>, comparison_direction = #mhlo<comparison_direction LT>} : (tensor<?xi32>, tensor<?xi32>) -> tensor<?xi1>
    %9 = mhlo.constant dense<3> : tensor<i32>
    %10 = mhlo.convert %arg0 : tensor<i32>
    %11 = "mhlo.reshape"(%10) : (tensor<i32>) -> tensor<1xi32>
    %12 = "mhlo.dynamic_broadcast_in_dim"(%9, %11) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<i32>, tensor<1xi32>) -> tensor<?xi32>
    %13 = mhlo.add %arg1, %12 : tensor<?xi32>
    %14 = "mhlo.select"(%8, %13, %arg1) : (tensor<?xi1>, tensor<?xi32>, tensor<?xi32>) -> tensor<?xi32>
    %15 = mhlo.convert %arg0 : tensor<i32>
    %16 = "mhlo.reshape"(%15) : (tensor<i32>) -> tensor<1xi32>
    %17 = mhlo.constant dense<1> : tensor<1xi32>
    %18 = "mhlo.concatenate"(%16, %17) {dimension = 0 : i64} : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32>
    %19 = "mhlo.dynamic_broadcast_in_dim"(%14, %18) {broadcast_dimensions = dense<0> : tensor<1xi64>} : (tensor<?xi32>, tensor<2xi32>) -> tensor<?x1xi32>
    %20 = "mhlo.concatenate"(%19) {dimension = 1 : i64} : (tensor<?x1xi32>) -> tensor<?x1xi32>
    %21 = "mhlo.gather"(%0, %20) {dimension_numbers = #mhlo.gather<offset_dims = [1], start_index_map = [0], index_vector_dim = 1>, indices_are_sorted = false, slice_sizes = dense<1> : tensor<1xi64>} : (tensor<3xf32>, tensor<?x1xi32>) -> tensor<?x1xf32>
    %22 = mhlo.convert %arg0 : tensor<i32>
    %23 = "mhlo.reshape"(%22) : (tensor<i32>) -> tensor<1xi32>
    %24 = "mhlo.dynamic_reshape"(%21, %23) : (tensor<?x1xf32>, tensor<1xi32>) -> tensor<?xf32>
    return %24 : tensor<?xf32>
  }
}
```

The error I see is

```
Traceback (most recent call last):
  File "/usr/local/google/home/mattjj/packages/jax/djax7.py", line 25, in <module>
    g(idxs)
  File "/usr/local/google/home/mattjj/packages/jax/jax/_src/api.py", line 447, in f_jitted
    out_flat = xla.xla_call(
  File "/usr/local/google/home/mattjj/packages/jax/jax/core.py", line 1954, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/google/home/mattjj/packages/jax/jax/core.py", line 1970, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/google/home/mattjj/packages/jax/jax/core.py", line 689, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/google/home/mattjj/packages/jax/jax/_src/dispatch.py", line 233, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/usr/local/google/home/mattjj/packages/jax/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/google/home/mattjj/packages/jax/jax/_src/dispatch.py", line 324, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/usr/local/google/home/mattjj/packages/jax/jax/_src/dispatch.py", line 934, in compile
    self._executable = XlaCompiledComputation.from_xla_computation(
  File "/usr/local/google/home/mattjj/packages/jax/jax/_src/dispatch.py", line 1052, in from_xla_computation
    compiled = compile_or_get_cached(backend, xla_computation, options,
  File "/usr/local/google/home/mattjj/packages/jax/jax/_src/dispatch.py", line 1006, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options, host_callbacks)
  File "/usr/local/google/home/mattjj/packages/jax/jax/_src/profiler.py", line 313, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/google/home/mattjj/packages/jax/jax/_src/dispatch.py", line 950, in backend_compile
    return backend.compile(built_c, compile_options=options)
  File "/usr/local/google/home/mattjj/packages/jax/jax/_src/iree.py", line 186, in compile
    iree_binary = iree.compiler.compile_str(
  File "/usr/local/google/home/mattjj/miniconda3/lib/python3.9/site-packages/iree/compiler/tools/core.py", line 277, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/mattjj/miniconda3/lib/python3.9/site-packages/iree/compiler/tools/binaries.py", line 196, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
/usr/local/google/home/mattjj/packages/jax/djax7.py:18:1: error: failed to legalize operation 'mhlo.dynamic_broadcast_in_dim' that was explicitly marked illegal
  return x[i]
^
compilation failed


Invoked with:
 iree-compile /usr/local/google/home/mattjj/miniconda3/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=llvm-cpu --iree-llvm-embedded-linker-path=/usr/local/google/home/mattjj/miniconda3/lib/python3.9/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.

> /usr/local/google/home/mattjj/miniconda3/lib/python3.9/site-packages/iree/compiler/tools/binaries.py(196)invoke_immediate()
-> raise CompilerToolError(process)
```

### Steps to reproduce your issue

Below are the files dumped by setting `IREE_SAVE_TEMPS` (except `core-output.bin`, which GitHub doesn't want to attach). I don't know the steps to actually run a reproducer from these, but I assume you do!

* [core-command-line.txt](https://github.com/iree-org/iree/files/9529355/core-command-line.txt)
* [core-input.mlir.txt](https://github.com/iree-org/iree/files/9529359/core-input.mlir.txt)
* [core-reproducer.mlir.txt](https://github.com/iree-org/iree/files/9529360/core-reproducer.mlir.txt)

### What component(s) does this issue relate to?

MLIR

### Version information

Current pypi head: 
```
$ python -m pip show iree-compiler iree-runtime
Name: iree-compiler
Version: 20220907.259
Summary: IREE Compiler API
Home-page:
Author: IREE Authors
Author-email: iree-discuss@googlegroups.com
License: Apache-2.0
Location: /usr/local/google/home/mattjj/miniconda3/lib/python3.9/site-packages
Requires: numpy, PyYAML
Required-by:
---
Name: iree-runtime
Version: 20220907.259
Summary: IREE Python Runtime Components
Home-page: https://github.com/iree-org/iree
Author: IREE Authors
Author-email: iree-discuss@googlegroups.com
License: Apache-2.0
Location: /usr/local/google/home/mattjj/miniconda3/lib/python3.9/site-packages
Requires: numpy, PyYAML
Required-by:
```

**Comment by silvasean** [comment]
This is a bug in MHLO -> Linalg lowering so not part of IREE per se.

https://github.com/tensorflow/mlir-hlo/blob/master/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc#L728

Staring at the code there, adding the known_expanding_dimensions attribute to dynamic_broadcast_in_dim might help.

**Comment by rsuderman** [comment]
I expect there are a decent number of these kind of dynamic shape bugs in mhlo->linalg so happy to see a new dynamic-jax has a new mechanism to generate them. Will put this as a P1 as we really want to start preparing for dynamic workloads.

**Comment by rsuderman** [comment]
@mattjj Looking further into this, this is potentially an illegal op? It is a bit weird because you are broacasting a `tensor<?xi32>` to a `tensor<?xi32>` which is only legal if `?==?` or the first `?` is 1. Its a bit weird to see an up broadcast where the starting shape is the one being broadcast.

@silvasean I know you mentioned there is a way to handle these weird broadcasting, any idea whether these concepts would port to the `mhlo` lowerings?

**Comment by silvasean** [comment]
In this case, in a private discussion with @mattjj there is actually a correlation here between %arg0 and the size involved. The broadcasting intent is statically known at the JAX level here and guaranteed not an error. I made some suggestions to @mattjj for how to potentially improve the emitted IR.

**Comment by jpienaar** [comment]
Any additional work needed here?
