### ISSUE TITLE
Failed to legalize `mhlo.pad`

### ISSUE THREAD

**Issue by hawkinsp** [openxla/iree#7614]
Repro:
```
from iree.compiler import compile_str

CODE = """
module  {
  func @main(%arg0: tensor<3x4x5xi32>) -> tensor<3x4x5xi32> {
    %0 = "mhlo.reverse"(%arg0) {dimensions = dense<2> : tensor<1xi64>} : (tensor<3x4x5xi32>) -> tensor<3x4x5xi32>
    %1 = "mhlo.slice"(%0) {limit_indices = dense<[3, 4, 4]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<[1, 1, 2]> : tensor<3xi64>} : (tensor<3x4x5xi32>) -> tensor<3x4x2xi32>
    %2 = "mhlo.slice"(%0) {limit_indices = dense<[3, 4, 5]> : tensor<3xi64>, start_indices = dense<[0, 0, 1]> : tensor<3xi64>, strides = dense<[1, 1, 2]> : tensor<3xi64>} : (tensor<3x4x5xi32>) -> tensor<3x4x2xi32>
    %3 = mhlo.maximum %1, %2 : tensor<3x4x2xi32>
    %4 = "mhlo.slice"(%3) {limit_indices = dense<[3, 4, 1]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<[1, 1, 2]> : tensor<3xi64>} : (tensor<3x4x2xi32>) -> tensor<3x4x1xi32>
    %5 = "mhlo.slice"(%3) {limit_indices = dense<[3, 4, 2]> : tensor<3xi64>, start_indices = dense<[0, 0, 1]> : tensor<3xi64>, strides = dense<[1, 1, 2]> : tensor<3xi64>} : (tensor<3x4x2xi32>) -> tensor<3x4x1xi32>
    %6 = mhlo.maximum %4, %5 : tensor<3x4x1xi32>
    %7 = "mhlo.slice"(%6) {limit_indices = dense<[3, 4, 0]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<3x4x1xi32>) -> tensor<3x4x0xi32>
    %8 = "mhlo.slice"(%3) {limit_indices = dense<[3, 4, 2]> : tensor<3xi64>, start_indices = dense<[0, 0, 2]> : tensor<3xi64>, strides = dense<[1, 1, 2]> : tensor<3xi64>} : (tensor<3x4x2xi32>) -> tensor<3x4x0xi32>
    %9 = mhlo.maximum %7, %8 : tensor<3x4x0xi32>
    %10 = "mhlo.slice"(%3) {limit_indices = dense<[3, 4, 1]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<3x4x2xi32>) -> tensor<3x4x1xi32>
    %11 = "mhlo.concatenate"(%10, %9) {dimension = 2 : i64} : (tensor<3x4x1xi32>, tensor<3x4x0xi32>) -> tensor<3x4x1xi32>
    %12 = mhlo.constant dense<0> : tensor<i32>
    %13 = "mhlo.pad"(%11, %12) {edge_padding_high = dense<[0, 0, 1]> : tensor<3xi64>, edge_padding_low = dense<0> : tensor<3xi64>, interior_padding = dense<[0, 0, 1]> : tensor<3xi64>} : (tensor<3x4x1xi32>, tensor<i32>) -> tensor<3x4x2xi32>
    %14 = mhlo.constant dense<0> : tensor<i32>
    %15 = "mhlo.pad"(%6, %14) {edge_padding_high = dense<0> : tensor<3xi64>, edge_padding_low = dense<[0, 0, 1]> : tensor<3xi64>, interior_padding = dense<[0, 0, 1]> : tensor<3xi64>} : (tensor<3x4x1xi32>, tensor<i32>) -> tensor<3x4x2xi32>
    %16 = mhlo.add %13, %15 : tensor<3x4x2xi32>
    %17 = "mhlo.slice"(%0) {limit_indices = dense<[3, 4, 5]> : tensor<3xi64>, start_indices = dense<[0, 0, 2]> : tensor<3xi64>, strides = dense<[1, 1, 2]> : tensor<3xi64>} : (tensor<3x4x5xi32>) -> tensor<3x4x2xi32>
    %18 = mhlo.maximum %16, %17 : tensor<3x4x2xi32>
    %19 = "mhlo.slice"(%0) {limit_indices = dense<[3, 4, 1]> : tensor<3xi64>, start_indices = dense<0> : tensor<3xi64>, strides = dense<1> : tensor<3xi64>} : (tensor<3x4x5xi32>) -> tensor<3x4x1xi32>
    %20 = "mhlo.concatenate"(%19, %18) {dimension = 2 : i64} : (tensor<3x4x1xi32>, tensor<3x4x2xi32>) -> tensor<3x4x3xi32>
    %21 = mhlo.constant dense<0> : tensor<i32>
    %22 = "mhlo.pad"(%20, %21) {edge_padding_high = dense<0> : tensor<3xi64>, edge_padding_low = dense<0> : tensor<3xi64>, interior_padding = dense<[0, 0, 1]> : tensor<3xi64>} : (tensor<3x4x3xi32>, tensor<i32>) -> tensor<3x4x5xi32>
    %23 = mhlo.constant dense<0> : tensor<i32>
    %24 = "mhlo.pad"(%16, %23) {edge_padding_high = dense<[0, 0, 1]> : tensor<3xi64>, edge_padding_low = dense<[0, 0, 1]> : tensor<3xi64>, interior_padding = dense<[0, 0, 1]> : tensor<3xi64>} : (tensor<3x4x2xi32>, tensor<i32>) -> tensor<3x4x5xi32>
    %25 = mhlo.add %22, %24 : tensor<3x4x5xi32>
    %26 = "mhlo.reverse"(%25) {dimensions = dense<2> : tensor<1xi64>} : (tensor<3x4x5xi32>) -> tensor<3x4x5xi32>
    return %26 : tensor<3x4x5xi32>
  }
}
"""

compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
```

Get:
```
$ python t.py
Traceback (most recent call last):
  File "t.py", line 38, in <module>
    compiled_flatbuffer = compile_str(CODE, target_backends=["dylib"], input_type="mhlo")
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/core.py", line 262, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/binaries.py", line 201, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool ireec
Diagnostics:
<stdin>:17:11: error: failed to legalize operation 'mhlo.pad' that was explicitly marked illegal
    %13 = "mhlo.pad"(%11, %12) {edge_padding_high = dense<[0, 0, 1]> : tensor<3xi64>, edge_padding_low = dense<0> : tensor<3xi64>, interior_padding = dense<[0, 0, 1]> : tensor<3xi64>} : (tensor<3x4x1xi32>, tensor<i32>) -> tensor<3x4x2xi32>
          ^
<stdin>:3:3: note: called from
  func @main(%arg0: tensor<3x4x5xi32>) -> tensor<3x4x5xi32> {
  ^
<stdin>:2:1: error: conversion from source -> vm failed
module  {
^


Invoked with:
 ireec /usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/ireec - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/usr/local/google/home/phawkins/.pyenv/versions/py373a/lib/python3.7/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by hanhanW** [comment]
mhlo.pad with `interior_padding` lowering is not supported at this moment. We don't know how to represent it in Linalg level currently.

After roughly thinking a bit, I think they could be stride things in `tensor.extract_slice`. We probably have to extend linalg.pad_tensor op semantic to carry the information. However, incomplete tiles could be a big issue here. (say that the size is not a multiple of `interior_padding + 1`.

Another approach could be representing it as a `linalg.generic` op. We can use `scf.if` and `linalg.index` to decide which value to yield. There is a transform that legalize `linalg.pad_tensor` op to `linalg.generic` op. I don't remember the details now, but probably can reference to that implementation.

**Comment by rsuderman** [comment]
Validated that this now compiles.
