### ISSUE TITLE
Lowering failure for i1 mhlo.dot_general

### ISSUE THREAD

**Issue by hawkinsp** [openxla/iree#9292]
```
import iree.compiler

CODE = """
#loc0 = loc(unknown)
module @jit_prim_fun.0 {
  func.func public @main(%arg0: tensor<3x5xi1> loc(unknown), %arg1: tensor<2x5xi1> loc(unknown)) -> tensor<3x2xi1> {
    %0 = "mhlo.dot_general"(%arg0, %arg1) {dot_dimension_numbers = #mhlo.dot<lhs_contracting_dimensions = [1], rhs_contracting_dimensions = [1]>, precision_config = [#mhlo<"precision DEFAULT">, #mhlo<"precision DEFAULT">]} : (tensor<3x5xi1>, tensor<2x5xi1>) -> tensor<3x2xi1> loc(#loc1)
    return %0 : tensor<3x2xi1> loc(#loc0)
  } loc(#loc0)
} loc(#loc0)
#loc1 = loc("jit(dot_general)/jit(main)/dot_general[dimension_numbers=(((1,), (1,)), ((), ())) precision=None preferred_element_type=None]"("/Users/phawkins/p/jax/tests/lax_test.py":1169:1))
"""

iree_binary = iree.compiler.compile_str(
    CODE, target_backends=["dylib"], input_type="mhlo")

```

```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 14, in <module>
    iree_binary = iree.compiler.compile_str(
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/core.py", line 293, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 200, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
<unknown>:0: error: 'linalg.yield' op type of yield operand 1 ('i1') doesn't match the element type of the enclosing linalg.generic op ('i8')
/Users/phawkins/p/jax/tests/lax_test.py:1169:1: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm", "embedded-elf-x86_64", {cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
      return lax.dot_general(lhs, rhs, dimension_numbers)
^
/Users/phawkins/p/jax/tests/lax_test.py:1169:1: error: failed to serialize executables
      return lax.dot_general(lhs, rhs, dimension_numbers)
^
compilation failed


Invoked with:
 iree-compile /Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false

```

**Comment by jpienaar** [comment]
This fails after TypePropagation see local reproducer below

```mlir
// configuration: -pass-pipeline='hal.executable(hal.executable.variant(builtin.module(func.func(iree-codegen-type-propagation))))' -mlir-disable-threading -verify-each
#device_target_cpu = #hal.device.target<"cpu", {executable_targets = [#hal.executable.target<"llvm", "embedded-elf-x86_64", {cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>]}>
#executable_layout0 = #hal.executable.layout<push_constants = 0, sets = [#hal.descriptor_set.layout<0, bindings = [#hal.descriptor_set.binding<0, storage_buffer>, #hal.descriptor_set.binding<1, storage_buffer>]>]>
#executable_layout1 = #hal.executable.layout<push_constants = 0, sets = [#hal.descriptor_set.layout<0, bindings = [#hal.descriptor_set.binding<0, storage_buffer>, #hal.descriptor_set.binding<1, storage_buffer>, #hal.descriptor_set.binding<2, storage_buffer>]>]>
#executable_target_embedded_elf_x86_64_ = #hal.executable.target<"llvm", "embedded-elf-x86_64", {cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
#loc0 = loc(unknown)
#loc1 = loc("jit(dot_general)/jit(main)/dot_general[dimension_numbers=(((1,), (1,)), ((), ())) precision=None preferred_element_type=None]"("/Users/phawkins/p/jax/tests/lax_test.py":1169:1))
#map0 = affine_map<()[s0] -> (s0 ceildiv 5)>
#map1 = affine_map<()[s0] -> (s0 ceildiv 2)>
#translation = #iree_codegen.translation_info<CPUDoubleTilingExpert workload_per_wg = [2, 5]>
module @jit_prim_fun_0 attributes {hal.device.targets = [#device_target_cpu]} {
  hal.executable private @main_dispatch_1 {
    hal.executable.variant public @embedded_elf_x86_64, target = #executable_target_embedded_elf_x86_64_ {
      hal.executable.export public @main_dispatch_1 ordinal(0) layout(#executable_layout1) loc(#loc1)
      builtin.module {
        func.func @main_dispatch_1() {
          %c0 = arith.constant 0 : index loc(#loc1)
          %false = arith.constant false loc(#loc1)
          %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:3x5xi8> loc(#loc0)
          %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:5x2xi8> loc(#loc1)
          %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<writeonly:3x2xi8> loc(#loc1)
          %3 = flow.dispatch.tensor.load %0, offsets = [0, 0], sizes = [3, 5], strides = [1, 1] : !flow.dispatch.tensor<readonly:3x5xi8> -> tensor<3x5xi8> loc(#loc1)
          %4 = arith.trunci %3 : tensor<3x5xi8> to tensor<3x5xi1> loc(#loc1)
          %5 = flow.dispatch.tensor.load %1, offsets = [0, 0], sizes = [5, 2], strides = [1, 1] : !flow.dispatch.tensor<readonly:5x2xi8> -> tensor<5x2xi8> loc(#loc1)
          %6 = arith.trunci %5 : tensor<5x2xi8> to tensor<5x2xi1> loc(#loc1)
          %7 = linalg.init_tensor [3, 2] : tensor<3x2xi1> loc(#loc1)
          %8 = linalg.fill ins(%false : i1) outs(%7 : tensor<3x2xi1>) -> tensor<3x2xi1> loc(#loc1)
          %9 = linalg.matmul ins(%4, %6 : tensor<3x5xi1>, tensor<5x2xi1>) outs(%8 : tensor<3x2xi1>) -> tensor<3x2xi1> loc(#loc1)
          %10 = arith.extui %9 : tensor<3x2xi1> to tensor<3x2xi8> loc(#loc1)
          flow.dispatch.tensor.store %10, %2, offsets = [0, 0], sizes = [3, 2], strides = [1, 1] : tensor<3x2xi8> -> !flow.dispatch.tensor<writeonly:3x2xi8> loc(#loc1)
          return loc(#loc1)
        } loc(#loc1)
      } loc(#loc1)
    } loc(#loc1)
  } loc(#loc1)
} loc(#loc0)
```

**Comment by rsuderman** [comment]
Verified to compile
