### ISSUE TITLE
Lowering failure for i1 mhlo.gather

### ISSUE THREAD

**Issue by hawkinsp** [openxla/iree#9294]
Repro:

```
import iree.compiler

CODE = """
#loc0 = loc(unknown)
module @jit_prim_fun.0 {
  func.func public @main(%arg0: tensor<10xi1> loc(unknown), %arg1: tensor<3x1xi32> loc(unknown)) -> tensor<3x2xi1> {
    %0 = "mhlo.gather"(%arg0, %arg1) {dimension_numbers = #mhlo.gather<offset_dims = [1], start_index_map = [0], index_vector_dim = 1>, indices_are_sorted = false, slice_sizes = dense<2> : tensor<1xi64>} : (tensor<10xi1>, tensor<3x1xi32>) -> tensor<3x2xi1> loc(#loc1)
    return %0 : tensor<3x2xi1> loc(#loc0)
  } loc(#loc0)
} loc(#loc0)
#loc1 = loc("jit(gather)/jit(main)/gather[dimension_numbers=GatherDimensionNumbers(offset_dims=(1,), collapsed_slice_dims=(), start_index_map=(0,)) slice_sizes=(2,) unique_indices=False indices_are_sorted=False mode=GatherScatterMode.PROMISE_IN_BOUNDS fill_value=None]"("/Users/phawkins/p/jax/tests/lax_test.py":2208:1))
"""

iree_binary = iree.compiler.compile_str(
    CODE, target_backends=["dylib"], input_type="mhlo")
```

Output:
```
Traceback (most recent call last):
  File "/Users/phawkins/p/jax/t.py", line 14, in <module>
    iree_binary = iree.compiler.compile_str(
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/core.py", line 293, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/binaries.py", line 200, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
/Users/phawkins/p/jax/tests/lax_test.py:2208:1: error: 'tensor.extract' op failed to verify that result type matches element type of tensor
    rand_idxs = lambda: rng_idx(idxs.shape, idxs.dtype)
^
/Users/phawkins/p/jax/tests/lax_test.py:2208:1: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm", "embedded-elf-x86_64", {cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
    rand_idxs = lambda: rng_idx(idxs.shape, idxs.dtype)
^
/Users/phawkins/p/jax/tests/lax_test.py:2208:1: error: failed to serialize executables
    rand_idxs = lambda: rng_idx(idxs.shape, idxs.dtype)
^
compilation failed


Invoked with:
 iree-compile /Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-compile - --iree-input-type=mhlo --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=dylib --iree-mlir-to-vm-bytecode-module --iree-llvm-embedded-linker-path=/Users/phawkins/.pyenv/versions/py310/lib/python3.10/site-packages/iree/compiler/tools/../_mlir_libs/iree-lld --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false
```

**Comment by jpienaar** [comment]
Pipeline failed while executing [`mlir::iree_compiler::IREE::HAL::TranslateExecutablesPass` on 'hal.executable' operation: @main_dispatch_0, `mlir::iree_compiler::IREE::HAL::TranslateTargetExecutableVariantsPass` on 'hal.executable.variant' operation: @embedded_elf_x86_64, `TypePropagation` on 'func.func' operation: @main_dispatch_0]: reproducer generated at `/tmp/core-reproducer.mlir`

```mlir

















// configuration: -pass-pipeline='hal.executable(hal.executable.variant(builtin.module(func.func(iree-codegen-type-propagation))))' -mlir-disable-threading -verify-each
#device_target_cpu = #hal.device.target<"cpu", {executable_targets = [#hal.executable.target<"llvm", "embedded-elf-x86_64", {cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>]}>
#executable_layout = #hal.executable.layout<push_constants = 0, sets = [#hal.descriptor_set.layout<0, bindings = [#hal.descriptor_set.binding<0, storage_buffer>, #hal.descriptor_set.binding<1, storage_buffer>, #hal.descriptor_set.binding<2, storage_buffer>]>]>
#executable_target_embedded_elf_x86_64_ = #hal.executable.target<"llvm", "embedded-elf-x86_64", {cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf"}>
#loc0 = loc(unknown)
#loc1 = loc("jit(gather)/jit(main)/gather[dimension_numbers=GatherDimensionNumbers(offset_dims=(1,), collapsed_slice_dims=(), start_index_map=(0,)) slice_sizes=(2,) unique_indices=False indices_are_sorted=False mode=GatherScatterMode.PROMISE_IN_BOUNDS fill_value=None]"("/Users/phawkins/p/jax/tests/lax_test.py":2208:1))
#map = affine_map<(d0, d1) -> (d0, d1)>
module @jit_prim_fun_0 attributes {hal.device.targets = [#device_target_cpu]} {
  hal.executable private @main_dispatch_0 {
    hal.executable.variant public @embedded_elf_x86_64, target = #executable_target_embedded_elf_x86_64_ {
      hal.executable.export public @main_dispatch_0 ordinal(0) layout(#executable_layout) loc(#loc1)
      builtin.module {
        func.func @main_dispatch_0() {
          %c0 = arith.constant 0 : index loc(#loc1)
          %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:3x1xi32> loc(#loc0)
          %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:10xi8> loc(#loc0)
          %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<writeonly:3x2xi8> loc(#loc1)
          %3 = flow.dispatch.tensor.load %0, offsets = [0, 0], sizes = [3, 1], strides = [1, 1] : !flow.dispatch.tensor<readonly:3x1xi32> -> tensor<3x1xi32> loc(#loc1)
          %4 = flow.dispatch.tensor.load %1, offsets = [0], sizes = [10], strides = [1] : !flow.dispatch.tensor<readonly:10xi8> -> tensor<10xi8> loc(#loc1)
          %5 = arith.trunci %4 : tensor<10xi8> to tensor<10xi1> loc(#loc1)
          %6 = linalg.init_tensor [3, 2] : tensor<3x2xi1> loc(#loc1)
          %7 = linalg.generic {indexing_maps = [#map], iterator_types = ["parallel", "parallel"]} outs(%6 : tensor<3x2xi1>) {
          ^bb0(%arg0: i1 loc("jit(gather)/jit(main)/gather[dimension_numbers=GatherDimensionNumbers(offset_dims=(1,), collapsed_slice_dims=(), start_index_map=(0,)) slice_sizes=(2,) unique_indices=False indices_are_sorted=False mode=GatherScatterMode.PROMISE_IN_BOUNDS fill_value=None]"("/Users/phawkins/p/jax/tests/lax_test.py":2208:1))):
            %9 = linalg.index 0 : index loc(#loc1)
            %10 = linalg.index 1 : index loc(#loc1)
            %11 = tensor.extract %3[%9, %c0] : tensor<3x1xi32> loc(#loc1)
            %12 = arith.index_cast %11 : i32 to index loc(#loc1)
            %13 = arith.addi %12, %10 : index loc(#loc1)
            %14 = tensor.extract %5[%13] : tensor<10xi1> loc(#loc1)
            linalg.yield %14 : i1 loc(#loc1)
          } -> tensor<3x2xi1> loc(#loc1)
          %8 = arith.extui %7 : tensor<3x2xi1> to tensor<3x2xi8> loc(#loc1)
          flow.dispatch.tensor.store %8, %2, offsets = [0, 0], sizes = [3, 2], strides = [1, 1] : tensor<3x2xi8> -> !flow.dispatch.tensor<writeonly:3x2xi8> loc(#loc1)
          return loc(#loc1)
        } loc(#loc1)
      } loc(#loc1)
    } loc(#loc1)
  } loc(#loc1)
  func.func @main(%arg0: !hal.buffer_view loc(unknown), %arg1: !hal.buffer_view loc(unknown)) -> !hal.buffer_view attributes {iree.abi.stub} {
    %c0 = arith.constant 0 : index loc(#loc1)
    %c10 = arith.constant 10 : index loc(#loc0)
    %c12 = arith.constant 12 : index loc(#loc0)
    %c6 = arith.constant 6 : index loc(#loc1)
    %c1 = arith.constant 1 : index loc(#loc0)
    %c268435488_i32 = arith.constant 268435488 : i32 loc(#loc0)
    %c3 = arith.constant 3 : index loc(#loc1)
    %c2 = arith.constant 2 : index loc(#loc1)
    %c318767112_i32 = arith.constant 318767112 : i32 loc(#loc0)
    %c1_i32 = arith.constant 1 : i32 loc(#loc0)
    hal.buffer_view.assert<%arg0 : !hal.buffer_view> message("tensor") shape([%c10]) type(%c318767112_i32) encoding(%c1_i32) loc(#loc0)
    %0 = stream.tensor.import %arg0 : !hal.buffer_view -> tensor<10xi1> in !stream.resource<external>{%c10} loc(#loc0)
    hal.buffer_view.assert<%arg1 : !hal.buffer_view> message("tensor") shape([%c3, %c1]) type(%c268435488_i32) encoding(%c1_i32) loc(#loc0)
    %1 = stream.tensor.import %arg1 : !hal.buffer_view -> tensor<3x1xi32> in !stream.resource<external>{%c12} loc(#loc0)
    %2 = stream.resource.alloc uninitialized : !stream.resource<external>{%c6} loc(#loc1)
    %3 = stream.cmd.execute with(%1 as %arg2: !stream.resource<external>{%c12}, %0 as %arg3: !stream.resource<external>{%c10}, %2 as %arg4: !stream.resource<external>{%c6}) {
      stream.cmd.dispatch @main_dispatch_0::@main_dispatch_0[%c3, %c2] {
        ro %arg2[%c0 for %c12] : !stream.resource<external>{%c12},
        ro %arg3[%c0 for %c10] : !stream.resource<external>{%c10},
        wo %arg4[%c0 for %c6] : !stream.resource<external>{%c6}
      } attributes {hal.interface.bindings = [#hal.interface.binding<0, 0>, #hal.interface.binding<0, 1>, #hal.interface.binding<0, 2>]} loc(#loc1)
    } => !stream.timepoint loc(#loc1)
    %4 = stream.timepoint.await %3 => %2 : !stream.resource<external>{%c6} loc(#loc1)
    %5 = stream.tensor.export %4 : tensor<3x2xi1> in !stream.resource<external>{%c6} -> !hal.buffer_view loc(#loc0)
    return %5 : !hal.buffer_view loc(#loc0)
  } loc(#loc0)
} loc(#loc0)
```

**Comment by rsuderman** [comment]
Validated compilation succeeds at iree head
